### ISSUE TITLE
What font is used in the screenshot?

### ISSUE THREAD

**Issue by danmclaren92** [idleberg/Paraiso.tmTheme#2]
Love your theme, just wondering what font is used in your example screenshot?

**Comment by danmclaren92** [comment]
It's Deja Vu Sans Mono for anyone else that might have been wondering.

**Comment by idleberg** [comment]
Actually, it should be [Menlo](https://github.com/chriskempson/base16-builder/blob/master/templates/preview/html.erb#L11)
